"""extra changes if any

Revision ID: e474b5f397db
Revises: 124d6939b05c
Create Date: 2022-02-08 18:16:33.768738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e474b5f397db'
down_revision = '124d6939b05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
